version: "3"

services:
    nginx:
        image: nginx
        ports:
            - "5252:80"
        volumes:
            - ./:/var/www/
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
        container_name: app_nginx
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: ./.docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        container_name: app
        depends_on:
            - db

    db:
        image: postgres:latest
        restart: always
        ports:
            - "3434:5432"
        volumes:
            - ./tmp/postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=laravel
        container_name: app_db

    npm:
        build:
            context: .
            dockerfile: .docker/npm/Dockerfile
        container_name: npm
        volumes:
            - ./:/var/www/
        ports:
            - "5173:5173"

