name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      posts-db-testing:
        image: postgres
        env:
          POSTGRES_DB: laravel-test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer update
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    # - name: Test postgres connection
    #   run: psql postgres://postgres:postgres@localhost:5432/postgres -c 'SELECT 1;'
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        # DB_HOST: localhost
        DB_CONNECTION: pgsql
        DB_DATABASE: laravel-test
        DB_PORT: 5432
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
      run: php artisan test
